module.exports = ["Aerobics",
"Baseball",
"Basketball",
"Bicycling",
"Body Leverage/Bodyweight Training",
"Bodybuilding",
"Boot Camps",
"Boxing",
"Cardio Machines",
"Choreography",
"Circuit Training",
"Core Conditioning",
"Cross Country",
"Cycling",
"Dancing",
"Diving",
"Equestrian",
"Football",
"Golfing",
"Gymnastics",
"Gyrotonic, Gyrokinesis",
"Hiking",
"Hockey",
"Ice Skating",
"Jogging",
"Kettlebells",
"Kickboxing",
"Lacrosse",
"Martial Arts",
"Meditation",
"Mind &amp; Body",
"Mixed Martial Arts (MMA)",
"Nia",
"Nordic Walking",
"Personal Training",
"Pilates",
"Roller Blading",
"Rowing",
"Running",
"Skiing",
"Snowboarding",
"Soccer",
"Softball",
"Stretching/Flexibility",
"Surfing",
"Swimming",
"Tai Chi",
"Tennis",
"Track and Field",
"Trail Running",
"Triathlon",
"TRX (Suspension Training)",
"Volleyball",
"Walking",
"Water Fitness",
"Water Polo",
"Wrestling",
"Yoga",
"Zumba (Latin Dance)"]
