module.exports = ["Aerobics",
"Athletic Training",
"Back Pain Prevention/Postrehab",
"Biomechanics",
"Bodybuilding",
"Cardio Workouts",
"Clinical Exercise Physiologist",
"Core Training",
"Corporate Wellness",
"Diet and Nutrition",
"Executive Fitness",
"Exercise Physiology",
"Family Fitness",
"Fat Loss",
"Fitness Assessment",
"Fitness Education",
"Flexibility",
"Food and Cooking",
"Group Exercise",
"Injury Prevention",
"Kickboxing",
"Kids' Fitness",
"Kinesiology",
"Lifestyle Coaching",
"Lower Back Pain",
"Massage Therapy",
"Medical Fitness for Chronic Conditions",
"Men's Fitness",
"Mind-Body Fitness",
"Nutrition ",
"Nutrition Coaching",
"Personal Training",
"Physical Therapy",
"Plyometrics",
"Postnatal Fitness",
"Postrehab/Injury Recovery",
"Prenatal Fitness",
"Rehabilitation",
"Senior Fitness",
"Speed and Agility Training",
"Sports Conditioning",
"Sports Nutrition",
"Strength Training",
"Stress Management",
"Toning and General Fitness",
"Water Fitness",
"Weight Loss",
"Weight Management",
"Weight Training",
"Wellness Coaching",
"Wellness/Preventive",
"Women's Fitness"]